---
title: ""
output:
  html_document:
    df_print: paged
---



# Enunciado proyecto final Análisis de Datos 2019-2020


## Parte A:  de  limpieza y selección de factores  para el modelo de datos.


### Pregunta A.1 (**1 punto.**)

Explicar modelo y  el código el la carga inicial de datos.


### Pregunta A.2 (**2 puntos.**)

Con el conjunto de datos de set-a` en el la carga inicial de datos se  calculaba la media de HR  GCS Y RespRate y se guardaban en la tabla de datos final.  Ahora queremos seleccionar más variables (*Parameters*).  Así que hay elegir más parámetros de la lista de series temporales   y resumirlos con  uno o varios estadísticos que añadiremos a la tabla final.

Por ejemplo seleccionamos las variables NIDiasABP, NIMAP, NISysABP miden de distintas formas la tensión sanguínea. Seleccionaremos cada una de las variables por paciente  y devolveremos como estadśiticos el mínimo, el máximo, los 3 cuartiles...

Añadir  10 variables  eligiéndolas de la lista y con una análisis exploratorio seleccionar las 5  aportan más información  a la predicción de  supervivencia.


### Pregunta A.3 (**2 puntos.**)

Con la tabla ya curada y las 5  variables y los datos de perfil y de Outcome  presentar un análisis descriptivo multivariado.

## Parte B:  Aplicación de técnica de análisis multivariado

### Pregunta B.1 (**2 puntos.**)

Por tipo de UCI: cardíacas, médicas, quirúrgicas y traumatológicas predecir cuáles pacientes sobrevivirán a la hospitalización y cuáles no. 


### Pregunta B.2 (**2 puntos.**)

¿Hay diferencias por los descriptores generales  y el Tipo de UCI  en el momento de admisión del paciente?


### Pregunta B.3 (**1 punto.**)

 Explora  técnicas multivariadas para generar un índice de supervivencia a partir de los datos de perfil de admisión y de las 5 variables seleccionadas.
 